import { describe, it, expect, vi, beforeEach } from 'vitest';
import { GET } from '@/app/(backend)/api/staff/route';
import { NextRequest } from 'next/server';

vi.mock('@google/genai', () => {
  return {
    GoogleGenAI: class {
      models = {
        generateContent: vi.fn().mockResolvedValue({
          text: JSON.stringify({
            alerts: [
              {
                type: 'CROWD CONTROL',
                severity: 'HIGH',
                title: 'Test Bottleneck',
                description: 'Test description',
                action: 'Test action'
              }
            ]
          })
        })
      };
    },
    Type: {
      OBJECT: 'OBJECT',
      ARRAY: 'ARRAY',
      STRING: 'STRING'
    }
  };
});

describe('Staff API Route', () => {
  beforeEach(() => {
    process.env.GEMINI_API_KEY = 'test-key';
  });

  it('returns alerts generated by AI or falls back properly', async () => {
    const req = new NextRequest('http://localhost:3000/api/staff', {
      headers: {
        'x-real-ip': '127.0.0.1'
      }
    });
    const response = await GET(req);
    const data = await response.json();

    expect(response.status).toBe(200);
    expect(data).toHaveProperty('alerts');
    expect(data.alerts.length).toBeGreaterThan(0);
  });
});
